name: Sync JSON File

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update JSON file
        run: |
          echo "Fichier JSON mis à jour"
          # Remplacez cette ligne par le code pour mettre à jour le fichier JSON
          # Exemple: echo '{"example": "value"}' > data/items.json

      - name: Commit and push changes
        run: |
          git config --global user.email "steven.bordier@gmail.com"
          git config --global user.name "Steven-Moire"
          git add data/items.json
          git commit -m "Mise à jour du fichier JSON" || echo "No changes to commit"
          git push

      - name: List files
        run: ls -la

      - name: Check Git log
        run: git log -n 10
