name: Sync JSON File

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files
        run: ls -la

      - name: Check Git log
        run: git log -n 10

      - name: Update JSON file
        run: |
          echo '{
            "items": [
              { "id": "item1", "label": "14 petites assiettes", "checked": false },
              { "id": "item2", "label": "4 grandes assiettes", "checked": false },
              { "id": "item3", "label": "10 assiettes creuses", "checked": false },
              { "id": "item4", "label": "18 verres à whisky", "checked": false },
              { "id": "item5", "label": "6 verres à thé", "checked": false },
              { "id": "item6", "label": "12 fourchettes", "checked": false },
              { "id": "item7", "label": "14 couteaux", "checked": false },
              { "id": "item8", "label": "7 petites cuillères", "checked": false },
              { "id": "item9", "label": "9 grandes cuillères", "checked": false },
              { "id": "item10", "label": "1 Poêle + couvercle", "checked": false },
              { "id": "item11", "label": "1 Planche à découper forme poire verte", "checked": false },
              { "id": "item12", "label": "1 Passoire abîmée + 1 petite", "checked": false },
              { "id": "item13", "label": "1 rouleau pâtisserie", "checked": false },
              { "id": "item14", "label": "5 ramequins", "checked": false },
              { "id": "item15", "label": "2 plats (1 ovale, 1 rond)", "checked": false },
              { "id": "item16", "label": "2 écrases ail", "checked": false },
              { "id": "item17", "label": "1 ouvre-boîte", "checked": false },
              { "id": "item18", "label": "4 pots bol apéro", "checked": false },
              { "id": "item19", "label": "15 petites tasses", "checked": false },
              { "id": "item20", "label": "19 sous-tasses", "checked": false },
              { "id": "item21", "label": "10 tasses moyennes", "checked": false },
              { "id": "item22", "label": "1 théière", "checked": false },
              { "id": "item23", "label": "2 couvercles micro-onde", "checked": false },
              { "id": "item24", "label": "2 plateaux verts en plastique", "checked": false },
              { "id": "item25", "label": "3 dessous de plat", "checked": false },
              { "id": "item26", "label": "1 entonnoir", "checked": false },
              { "id": "item27", "label": "1 porte sopalin", "checked": false },
              { "id": "item28", "label": "1 économe", "checked": false },
              { "id": "item29", "label": "5 spatules bois", "checked": false },
              { "id": "item30", "label": "2 spatules plastiques", "checked": false },
              { "id": "item31", "label": "1 louche", "checked": false },
              { "id": "item32", "label": "1 passoire", "checked": false },
              { "id": "item33", "label": "1 grande cuillère", "checked": false },
              { "id": "item34", "label": "1 égouttoir vaisselle vert", "checked": false },
              { "id": "item35", "label": "1 chariot porte-légumes vert", "checked": false },
              { "id": "item36", "label": "5 tasses pot", "checked": false },
              { "id": "item37", "label": "1 sucrier", "checked": false },
              { "id": "item38", "label": "3 sous-tasses", "checked": false },
              { "id": "item39", "label": "1 gril", "checked": false },
              { "id": "item40", "label": "6 pots grès", "checked": false }
            ]
          }' > items.json

      - name: Configure Git
        run: |
          git config --global user.email "steven.bordier@gmail.com"
          git config --global user.name "Steven-Moire"

      - name: Commit and push changes
        run: |
          git add items.json
          git commit -m "Mise à jour du fichier JSON" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
